### ISSUE TITLE
MongoDB NodeJs driver updated

### ISSUE THREAD

**Issue by nomiali5** [sedouard/mongodb-mva#10]
MongoDB Node.js Driver most probably updated, because when you try to get docs.length after inserting a document in callback function it return undefined in module 4 crud functionality. A little change is required as 
"docs.ops.length" and the code changed respectively as
for(var i in docs.ops){
console.log(docs.ops[i].length);
}
docs in callback doesn't return a db object but a wrapper "ops" around that db object.

**Comment by roskelld** [comment]
I've been following the tutorial video for this, and wasted a day chasing down what undefined meant, only to find that things have been updated and _docs_ needs to be _docs.ops_ now.
