### ISSUE TITLE
"npm install" command not found - windows cmd 

### ISSUE THREAD

**Issue by ATidmore** [sedouard/mongodb-mva#3]
I cloned your repository and when navigating with the command line to accomplish Step 1 of Module 3 (i.e. do the "npm install" piece) , I encountered "'npm' is not recognized as an internal or external command..." --- Is there another piece of the puzzle I missed? Thanks!

**Comment by sedouard** [comment]
Hey @ATidmore you need to install Node.js :-). That error looks like  a windows error pretty sure. Just go to npmjs.org and download & install node.

Cheers!

Steve
