### ISSUE TITLE
Wrong db query in Module 2

### ISSUE THREAD

**Issue by ranjeet-floyd** [sedouard/mongodb-mva#4]
Given .. 
db.bank_data.find({ accounts: { $elemMatch : { "account_type": {$ne: "Checking"}, "currency": "USD", 'account_balance' : { $gt: 9900000 } } } } ).sort({ accounts.account_balance: -1 })

db.bank_data.find({ 'accounts.account_balance': {$gt: 9000000}, 'account.currency': 'USD' })

should be.....

db.bank_data.find({ 'accounts.account_balance': {$gt: 9000000}, 'accounts.currency': 'USD' })

db.bank_data.find({ accounts: { $elemMatch : { "account_type": {$ne: "Checking"}, "currency": "USD", 'account_balance' : { $gt: 9900000 } } } } ).sort({ "accounts.account_balance": -1 })

**Comment by sedouard** [comment]
Thanks @ranjeet-floyd. Looks like I made a typo.

https://github.com/sedouard/mongodb-mva/commit/7f23d8f45db7eb7aad5230dd22704440227ace05
